### ISSUE TITLE
Source of images?

### ISSUE THREAD

**Issue by adrianmoisey** [Templarian/slack-emoji-pokemon#1]
Hi

What is the source of the images in this pack? Where did you get them from?
Thanks

**Comment by Templarian** [comment]
They are extracted from the game, but to cut out the ugly details this site comes up in the first searches in google and seems to have extracted the images also... [here](http://www.pokexperto.net/index2.php?seccion=pokemongo/pokemon1). Save As will save all the images to a folder.

You could use the same Geeky Details section to resize them... http://templarian.com/2016/07/13/pokemon-slack-emojis/

Good luck on whatever project you are using them for, but know that ripping the resources out of the game is probably not all that "legal". This was really just a one off try to get the icons into Slack.

**Comment by adrianmoisey** [comment]
Which game? Go? (there are quite a few Pokemon games available)

**Comment by adrianmoisey** [comment]
Ah, I've just compared them, looks like they are from Go. Thanks.
